---
name: Data-Page-Balanced
version: 1.0.0
author:
  - 'Kim Ahlström <kim.ahlstrom@gmail.com>'
abstract: A data pager that will balance the number of entries per page.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Chained::Fast: 0
  Data::Page: 2
  Test::More: 0
  version: 0
provides:
  Data::Page::Balanced:
    file: lib/Data/Page/Balanced.pm
    version: 1.0.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
